image: node:17.0.1

variables:
  FF_USE_FASTZIP: "true"
  ARTIFACT_COMPRESSION_LEVEL: default
  CACHE_COMPRESSION_LEVEL: fast
  TRANSFER_METER_FREQUENCY: 5s

cache: &global_cache
  - key:
      files:
        - Gemfile.lock
      prefix: $CI_PROJECT_TITLE
    paths:
      - vendor/ruby
  - key:
      files:
        - yarn.lock
      prefix: $CI_PROJECT_TITLE
    paths:
      - node_modules/

before_script:
  - mkdir -p reports/

stages:
  - build
  - lint
  - test

yarn:
  stage: build
  cache:
    untracked: true
  script:
    - yarn install
  tags:
    - docker
  artifacts:
    paths:
      - reports/

run_linter:
  stage: lint
  cache:
    untracked: true
    policy: pull
  script:
    - yarn install
    - yarn lint
  tags:
    - docker

run_unit_tests:
  stage: test
  cache:
    untracked: true
    policy: pull
  script:
    - yarn install
    - yarn test --ci --forceExit --detectOpenHandles
  tags:
    - docker
  coverage: /All files\s*\|\s*([\d\.]+)/
  artifacts:
    paths:
      - reports/
    reports:
      junit:
        - reports/junit.xml
      cobertura: reports/coverage/cobertura-coverage.xml
